// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: pxnsbjlbjyigddcdauki

class SupabaseConfig {
  static const String supabaseUrl = 'https://pxnsbjlbjyigddcdauki.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4bnNiamxianlpZ2RkY2RhdWtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxNzY1OTUsImV4cCI6MjA4Nzc1MjU5NX0.QouqvTfRf0t29diNoTFobKODrCTGXFs8tJVduOodlI4';
}
